FROM python:3

LABEL maintainer="pabloromeo"

COPY qemu-arm-static /usr/bin/

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["flask", "run", "-h", "0.0.0.0"]
EXPOSE 5000/tcp
